# Generated by Django 6.1.1 on 2026-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='profile',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
